[pytest]
python_files = tests.py test_*.py *_test.py
testpaths = tests
addopts = --rootdir=tests
python_classes = Test*
python_functions = test_*
filterwarnings = 
    ignore::UserWarning:torchvision.io.image
    ignore::DeprecationWarning:torchvision.transforms._functional_pil
    ignore:Failed to load image Python extension:UserWarning
    ignore:.*BILINEAR.*deprecated.*:DeprecationWarning
    ignore:.*NEAREST.*deprecated.*:DeprecationWarning
    ignore:.*BICUBIC.*deprecated.*:DeprecationWarning
    ignore:fan_in_fan_out is set to False but the target module is.*:UserWarning 